export interface VietnamBank {
  id: string;
  name: string;
  shortName: string;
  code: string;
}

export const VIETNAM_BANKS: VietnamBank[] = [
  { id: "mbbank", name: "Ngân hàng TMCP Quân Đội (MBBank)", shortName: "MB Bank", code: "MB" },
  { id: "vietcombank", name: "Ngân hàng TMCP Ngoại Thương Việt Nam (Vietcombank)", shortName: "Vietcombank", code: "VCB" },
  { id: "techcombank", name: "Ngân hàng TMCP Kỹ Thương Việt Nam (Techcombank)", shortName: "Techcombank", code: "TCB" },
  { id: "vietinbank", name: "Ngân hàng TMCP Công Thương Việt Nam (VietinBank)", shortName: "VietinBank", code: "CTG" },
  { id: "bidv", name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)", shortName: "BIDV", code: "BIDV" },
  { id: "agribank", name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam (Agribank)", shortName: "Agribank", code: "VBA" },
  { id: "vpbank", name: "Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)", shortName: "VPBank", code: "VPB" },
  { id: "tpbank", name: "Ngân hàng TMCP Tiên Phong (TPBank)", shortName: "TPBank", code: "TPB" },
  { id: "acb", name: "Ngân hàng TMCP Á Châu (ACB)", shortName: "ACB", code: "ACB" },
  { id: "vib", name: "Ngân hàng TMCP Quốc Tế Việt Nam (VIB)", shortName: "VIB", code: "VIB" },
  { id: "sacombank", name: "Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank)", shortName: "Sacombank", code: "STB" },
  { id: "hdbank", name: "Ngân hàng TMCP Phát triển TP.HCM (HDBank)", shortName: "HDBank", code: "HDB" },
  { id: "msb", name: "Ngân hàng TMCP Hàng Hải Việt Nam (MSB)", shortName: "MSB", code: "MSB" },
  { id: "ocb", name: "Ngân hàng TMCP Phương Đông (OCB)", shortName: "OCB", code: "OCB" },
  { id: "seabank", name: "Ngân hàng TMCP Đông Nam Á (SeABank)", shortName: "SeABank", code: "SEAB" },
  { id: "lpbank", name: "Ngân hàng TMCP Lộc Phát Việt Nam (LPBank / LienVietPostBank)", shortName: "LPBank", code: "LPB" },
  { id: "bacabank", name: "Ngân hàng TMCP Bắc Á (Bac A Bank)", shortName: "Bac A Bank", code: "BAB" },
  { id: "eximbank", name: "Ngân hàng TMCP Xuất Nhập Khẩu Việt Nam (Eximbank)", shortName: "Eximbank", code: "EIB" },
  { id: "shb", name: "Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)", shortName: "SHB", code: "SHB" },
  { id: "namabank", name: "Ngân hàng TMCP Nam Á (Nam A Bank)", shortName: "Nam A Bank", code: "NAB" },
  { id: "abbank", name: "Ngân hàng TMCP An Bình (ABBANK)", shortName: "ABBANK", code: "ABB" },
  { id: "vietbank", name: "Ngân hàng TMCP Việt Nam Thương Tín (VietBank)", shortName: "VietBank", code: "VBB" },
  { id: "bvbank", name: "Ngân hàng TMCP Bản Việt (BVBank / VietCapitalBank)", shortName: "BVBank", code: "BVB" },
  { id: "kienlongbank", name: "Ngân hàng TMCP Kiên Long (Kienlongbank)", shortName: "Kienlongbank", code: "KLB" },
  { id: "pvcombank", name: "Ngân hàng TMCP Đại Chúng Việt Nam (PVcomBank)", shortName: "PVcomBank", code: "PVC" },
  { id: "oceanbank", name: "Ngân hàng Thương mại TNHH MTV Đại Dương (OceanBank)", shortName: "OceanBank", code: "OCEANBANK" },
  { id: "gpbank", name: "Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu (GPBank)", shortName: "GPBank", code: "GPB" },
  { id: "ncb", name: "Ngân hàng TMCP Quốc Dân (NCB)", shortName: "NCB", code: "NCB" },
  { id: "cb", name: "Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam (CBRank)", shortName: "CB Bank", code: "CBRANK" },
  { id: "scb", name: "Ngân hàng TMCP Sài Gòn (SCB)", shortName: "SCB", code: "SCB" },
  { id: "shinhan", name: "Ngân hàng TNHH MTV Shinhan Việt Nam (Shinhan Bank)", shortName: "Shinhan Bank", code: "SHINHAN" },
  { id: "woori", name: "Ngân hàng TNHH MTV Woori Việt Nam (Woori Bank)", shortName: "Woori Bank", code: "WOORI" },
  { id: "vrb", name: "Ngân hàng Liên doanh Việt - Nga (VRB)", shortName: "VRB", code: "VRB" },
  { id: "publicbank", name: "Ngân hàng TNHH MTV Public Việt Nam (Public Bank)", shortName: "Public Bank", code: "PBVN" },
  { id: "standardchartered", name: "Ngân hàng TNHH MTV Standard Chartered Việt Nam", shortName: "Standard Chartered", code: "SCVN" },
  { id: "hsbc", name: "Ngân hàng TNHH MTV HSBC Việt Nam", shortName: "HSBC", code: "HSBC" },
  { id: "uob", name: "Ngân hàng TNHH MTV UOB Việt Nam", shortName: "UOB", code: "UOB" },
  { id: "cimb", name: "Ngân hàng TNHH MTV CIMB Việt Nam", shortName: "CIMB", code: "CIMB" },
  { id: "citibank", name: "Ngân hàng Citibank Việt Nam", shortName: "Citibank", code: "CITI" },
  { id: "kasikorn", name: "Ngân hàng KASIKORNBANK - Chi nhánh TP.HCM", shortName: "KBank", code: "KBANK" },
  { id: "hongleong", name: "Ngân hàng TNHH MTV Hong Leong Việt Nam", shortName: "Hong Leong", code: "HLBVN" },
  { id: "indovina", name: "Ngân hàng TNHH Indovina (IVB)", shortName: "Indovina Bank", code: "IVB" },
  { id: "dongabank", name: "Ngân hàng TMCP Đông Á (DongA Bank)", shortName: "DongA Bank", code: "DAB" },
  { id: "pgbank", name: "Ngân hàng TMCP Thịnh vượng và Phát triển (PGBank)", shortName: "PGBank", code: "PGB" },
  { id: "saigonbank", name: "Ngân hàng TMCP Sài Gòn Công Thương (Saigonbank)", shortName: "Saigonbank", code: "SGB" },
  { id: "cake", name: "Cake by VPBank", shortName: "Cake by VPBank", code: "CAKE" },
  { id: "ubank", name: "Ubank by VPBank", shortName: "Ubank by VPBank", code: "UBANK" },
  { id: "viettelmoney", name: "Viettel Money", shortName: "Viettel Money", code: "VTLMONEY" },
  { id: "vnptmoney", name: "VNPT Money", shortName: "VNPT Money", code: "VNPTMONEY" },
  { id: "timoplus", name: "Timo Digital Bank", shortName: "Timo", code: "TIMO" }
];
